version: "3.9"
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=todoapp'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    ports:
      - '5444:5432'
    container_name: todoapp-postgre